// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:admin_product_app/core/constants/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: Env.firebaseWebApiKey,
    appId: '1:638770273403:web:6862a183809be9fe66d6de',
    messagingSenderId: '638770273403',
    projectId: 'admin-product-app-61dd0',
    authDomain: 'admin-product-app-61dd0.firebaseapp.com',
    databaseURL: 'https://admin-product-app-61dd0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-product-app-61dd0.firebasestorage.app',
    measurementId: 'G-T16N70B5HH',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: Env.firebaseAndroidApiKey,
    appId: '1:638770273403:android:bd0d5e68675810e866d6de',
    messagingSenderId: '638770273403',
    projectId: 'admin-product-app-61dd0',
    databaseURL: 'https://admin-product-app-61dd0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-product-app-61dd0.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.firebaseIosApiKey,
    appId: '1:638770273403:ios:44b4c280be0f8feb66d6de',
    messagingSenderId: '638770273403',
    projectId: 'admin-product-app-61dd0',
    databaseURL: 'https://admin-product-app-61dd0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-product-app-61dd0.firebasestorage.app',
    iosBundleId: 'com.example.adminProductApp',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: Env.firebaseMacosApiKey,
    appId: '1:638770273403:ios:44b4c280be0f8feb66d6de',
    messagingSenderId: '638770273403',
    projectId: 'admin-product-app-61dd0',
    databaseURL: 'https://admin-product-app-61dd0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-product-app-61dd0.firebasestorage.app',
    iosBundleId: 'com.example.adminProductApp',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: Env.firebaseWindowsApiKey,
    appId: '1:638770273403:web:702a571b5a79179c66d6de',
    messagingSenderId: '638770273403',
    projectId: 'admin-product-app-61dd0',
    authDomain: 'admin-product-app-61dd0.firebaseapp.com',
    databaseURL: 'https://admin-product-app-61dd0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-product-app-61dd0.firebasestorage.app',
    measurementId: 'G-5JQ0FTTVZ4',
  );
}
